UN 601 - focused article page
nationalarchives/ds-wagtail pull request #1066
Opened 2023-06-20 10:35 UTC by krishan-torchbox

Ticket URL: [UN - 601](https://national-archives.atlassian.net/browse/UN-601)

## About these changes

Changed the colours and size of the generic intro for focused article pages 

## How to check these changes

You need to create a focused article page under Stories from the collection

## Before assigning to reviewer, please make sure you have

- [ ] Checked things thoroughly before handing over to reviewer.
- [ ] Checked PR title starts with ticket number as per project conventions to help us keep track of changes.
- [ ] Ensured that PR includes only commits relevant to the ticket.
- [ ] Waited for all CI jobs to pass before requesting a review.
- [ ] Added/updated tests and documentation where relevant.

## Merging PR guidance

Follow [docs\developer-guide\contributing.md](https://nationalarchives.github.io/ds-wagtail/developer-guide/contributing/)

## Deployment guidance

Follow [docs\infra\environments.md](https://nationalarchives.github.io/ds-wagtail/infra/environments/)

2023-06-20 15:47 UTC, janehughes requested changes
Thanks Krishan - looking nice so far :) 

Comparing against the designs, there are a couple of things outstanding:

- The page intro should be underneath the hero image, whereas currently it's sitting above the image with the title:
Design: 
<img width="758" alt="image" src="https://github.com/nationalarchives/ds-wagtail/assets/8680557/28cffebb-fcf9-4e4f-acb7-f11d8b03e84c">

Current build: 
<img width="1186" alt="image" src="https://github.com/nationalarchives/ds-wagtail/assets/8680557/39cf41b0-8da5-40e0-a177-7e4822ca808f">

- We have some metadata missing from the page:
Design: 
<img width="729" alt="image" src="https://github.com/nationalarchives/ds-wagtail/assets/8680557/5d7d6cdc-5cc3-41d4-8277-bb1b2fcd6552">

I'm not sure if all of these are available from the BE but I noticed we have {{ page.author }} which is currently unstyled:

Current build:
<img width="635" alt="image" src="https://github.com/nationalarchives/ds-wagtail/assets/8680557/d60cd5b4-615a-4309-8e05-bdb507e34209">

Lets get this added to the metadata info above the image. We should be able to grab the publication date too without needing any custom BE but maybe one to check with @jamesbiggs. I'm not sure about the other metadata items or if they are part of the MVP - worth double checking that with Leanne.

Also a small styling thing - it looks like the title needs to be restricted in width as it doesn't flow to 100% of the hero in the designs.

Thank you!

2023-06-21 10:15 UTC, jamesbiggs commented
> Lets get this added to the metadata info above the image. We should be able to grab the publication date too without needing any custom BE but maybe one to check with @jamesbiggs. I'm not sure about the other metadata items or if they are part of the MVP - worth double checking that with Leanne.

Hi @krishan-torchbox and @janehughes, AFAIK the date should be available (pop me a slack message if you can't get it working!) and "in Records and research" and "part 5 of the civil war series" bit isn't part of MVP.

2023-06-22 08:24 UTC, janehughes commented
> > Lets get this added to the metadata info above the image. We should be able to grab the publication date too without needing any custom BE but maybe one to check with @jamesbiggs. I'm not sure about the other metadata items or if they are part of the MVP - worth double checking that with Leanne.
> 
> Hi @krishan-torchbox and @janehughes, AFAIK the date should be available (pop me a slack message if you can't get it working!) and "in Records and research" and "part 5 of the civil war series" bit isn't part of MVP.

Brilliant thanks @jamesbiggs and thank you for making these changes @krishan-torchbox this is looking 💯  now - nice work!
I'll approve it but hold off merging until the develop deployment issue is resolved. Thanks again!

2023-06-22 08:24 UTC, janehughes approved these changes

2023-06-22 08:53 UTC, merged