Replacing  wagtailfontawesome with wagtail-font-awesome-svg 0.0.2
nationalarchives/ds-wagtail pull request #209
Opened 2021-11-18 20:25 UTC by mozaki1

2021-11-19 16:57 UTC, jacobtoppm requested changes
I think per https://pypi.org/project/wagtail-font-awesome-svg/0.0.2/ you need to register the icons you want to use - currently they're not showing up in streamfield. The icons you need will be listed in the `Meta` classes of your custom streamfield blocks.

2021-11-23 16:49 UTC, AshTNA requested changes
Thanks for this @mozaki1 - I think the icons will need to be updated wherever it starts with `fa-` I think these exist still in `etna/collections/blocks.py`, `etna/home/blocks.py`, and `etna/records/blocks.py`

2021-11-24 10:13 UTC, mozaki1 commented
Hi Ash , thank you for the review, The new icons for wagtail-font-awesome-svg have slightly changed. They have changed the name of the icons also some are no longer there, 
you can check wagtail_hook.py, I have done the blocks for the insight page, you can check the admin page now after the upgrade.
before I do the other blocks I need a list of all approved icons so to hook them up in the register_icons function. you can see and browse from https://fontawesome.com/v5.15/icons?d=gallery&p=2&s=light,regular.

2021-11-25 17:53 UTC, AshTNA commented
Thanks @mozaki1 - I will go and find some icons tomorrow morning :+1:

2021-11-26 10:31 UTC, AshTNA commented
@mozaki1 i have added the icons :+1:

2021-11-26 12:16 UTC, mozaki1 commented
Thank you Ash , I will close this pull request and rebranch from the latest main, So to have only the changes needed rather than the long history associated with this branch.

2021-11-29 13:12 UTC, ababic commented on etna/insights/blocks.py
> +        icon = "star"
Just wanted to query this one?

2021-11-29 13:36 UTC, ababic approved these changes
LGTM :)

2021-11-29 13:37 UTC, merged