Feature/df 197
nationalarchives/ds-wagtail pull request #294
Opened 2022-04-12 11:12 UTC by AshTNA

Hi @ababic 

Would you be able to merge this PR?

It fixes https://national-archives.atlassian.net/browse/DF-197 and uses constants and a loop to render out the buckets instead of duplicating the HTML to render each bucket.

Thanks :+1:

2022-04-12 12:12 UTC, ababic requested changes
What you did works fine, but I think we could really benefit from introducing a new type here... I'm also very keen to get rid of that horrible `group:` prefix from all of the values (to match the updated filter fields).

2022-04-12 12:12 UTC, ababic commented on templates/search/blocks/search_landing_buckets.html
> +            {% endfor %}
```suggestion
            {% for bucket in buckets %}
                <li class="search-landing-buckets__list-item" >
                    {% bucket_count bucket_count_response bucket_data.count_key as bucket_count %}
                    <a href="{% url 'search-catalogue' %}?group={{ bucket.key }}" class="search-landing-buckets__link" aria-current="{% if bucket == current_bucket %}true{% else %}false{% endif %}>
                        {{ bucket.label }} ({{ bucket_count|intcomma }})
                    </a>
                </li>
            {% endfor %}
```

2022-04-12 12:12 UTC, ababic commented on templates/search/blocks/search_results.html
> +                <span class="search-results__metadata-count-highlight">{% if count < per_page %}{{ count }}{% else %}{{ per_page }}{% endif %}</span> (of {{ count|intcomma }}) result{{ count|pluraliz
```suggestion
                <span class="search-results__metadata-count-highlight">{% if count < per_page %}{{ count }}{% else %}{{ per_page }}{% endif %}</span> (of {{ count|intcomma }}) result{{ count|pluralize}} for "{{ form.q.value|default:'*' }}" in "{{ current_bucket.label }}"</p>
```

2022-04-12 12:12 UTC, ababic commented on templates/search/blocks/website_search_buckets.html
> +        {% endfor %}
```suggestion
        {% for bucket in buckets %}
            <li class="search-buckets__list-item--website" data-current="{% if bucket == current_bucket %}true{% else %}false{% endif %}">
                {% bucket_count bucket_count_response bucket_data.count_key as bucket_count %}
                <a href="?{% if form.q.value %}q={{ form.q.value }}&{% endif %}group={{ bucket.key }}" class="search-buckets__link" aria-current="{% if bucket == current_bucket %}true{% else %}false{% endif %}">
                    {{ bucket.label }} ({{ bucket_count|intcomma }})
                </a>
            </li>
        {% endfor %}
```

2022-04-13 09:33 UTC, AshTNA commented
Looks good, thanks @ababic

2022-04-13 09:58 UTC, merged