Feature/search highlighting
nationalarchives/ds-wagtail pull request #295
Opened 2022-04-13 11:28 UTC by AshTNA

Hi @ababic 

Would you be able to merge this PR if all is OK?

Thanks :+1:

2022-04-13 13:09 UTC, ababic requested changes
Thanks for the quick turnaround @AshTNA. I think we could simplify things somewhat by creating a 'filter' instead, though

2022-04-13 13:42 UTC, AshTNA commented
@ababic 

Will do :+1:

2022-04-13 14:19 UTC, ababic commented on etna/search/templatetags/search_tags.py
> +    print(raw_html)
@AshTNA Remember to tidy up :)

2022-04-13 14:20 UTC, AshTNA commented on etna/search/templatetags/search_tags.py
> +    print(raw_html)
@ababic Whoops!

2022-04-14 10:59 UTC, ababic approved these changes
Nice work @AshTNA! LGTM

2022-04-14 11:00 UTC, merged