UN-191: Javascript enhancements for Insights
nationalarchives/ds-wagtail pull request #330
Opened 2022-05-11 11:49 UTC by JamesWChan

Hi @AshTNA,

This PR adds JavaScript enhancements for Insight pages. The enhancements are:

- Collapsable/expandable sections on mobile
- Progress indication within the sidebar navigation on desktop
- Smooth scrolling when using the navigation jumplinks on desktop

I've split the code into modules and placed the modules in an appropriate subfolder (e.g. all modules relating to the mobile accordion are in an accordion_functionality folder). I've tested the enhancements on desktop/mobile and in Chrome, Firefox, Safari, Edge, and IE11 (there are a few issues with IE11 but I'll fix them in a separate PR).

2022-05-11 15:14 UTC, AshTNA requested changes
Hi @JamesWChan 

Nice work. I commented on a few code things, and also discovered a few things:

- After resizing the page multiple times and then clicking a jumplink, i'm prevented from scrolling for a few seconds. I think extra event listeners might be being added everytime a resize happens.
- After resizing the screen, when clicking the jumplinks, it seems that the highlighting only reappears when the user scrolls again. I think this is related to the resize issue in the previous point.
- Is it OK that you can click multiple jumplinks quickly and make the page scroll all over the place? Maybe the jumplinks could be disabled while scrolling, or make it so a user scrolling manually themselves cancels any active/pending animation, so they can easily exit the auto scrolling? 
- The scroll animation, and the jumplink highlighting doesn't seem to work on Chrome on Windows at all for me. 
- The jumplinks are not stickied on IE11, is this OK?
- Will the insights pages be refactored? It looks like a lot of headings with no content become jumplinks, which is confusing on mobile. For example the "Introduction" heading on the Shakespeare page, or "The protest march" on Mangrove Nine. 
- This is a very minor thing, but on the mobile headings, when they expand should the triangle flip to show it's expanded? 

Thanks

2022-05-12 20:36 UTC, JamesWChan commented on scripts/src/insights.js
> +    const $windowWidth = $(window).width();
Decided just to remove the variable altogether and just went with `$(window).width()`

2022-05-12 20:36 UTC, JamesWChan commented on scripts/src/insights.js
> +            if(e.which === 13 || e.which === 32) {
Good spot, thank you. Careless on my part. I've changed that now.

2022-05-12 20:36 UTC, JamesWChan commented on templates/insights/insights_index_page.html
> +        src="https://code.jquery.com/jquery-3.6.0.min.js"
Done.

2022-05-12 20:36 UTC, JamesWChan commented on templates/insights/insights_page.html
> +        src="https://code.jquery.com/jquery-3.6.0.min.js"
Done.

2022-05-12 20:36 UTC, JamesWChan commented on scripts/src/insights.js
> +                if(e.which === 13 || e.which === 32) {
Done.

2022-05-13 11:24 UTC, JamesWChan commented
Hi @AshTNA,

Thanks for the review. Just to address some points:

- Regarding jumplinks in IE 11: IE11 doesn't support sticky positioning so I'd have to find a workaround. I did check with Gwyn and he said it was okay as it was but I can address this issue along with some IE11 bugs in another PR if it's required.
- Regarding headings with no content: editors will be adding content so empty headings won't appear. But we can always add a rule in Wagtail that will prevent a section from having a heading only (i.e. if a heading is added, content will need to be added too).

2022-05-13 11:26 UTC, AshTNA approved these changes

2022-05-13 11:27 UTC, merged

2022-05-13 11:28 UTC, AshTNA commented
All good :+1: