UN-175
nationalarchives/ds-wagtail pull request #481
Opened 2022-10-06 09:41 UTC by JohnHeeryTNA

Related ticket(s):
-  https://national-archives.atlassian.net/browse/UN-175

This is the combined BE and FE work for the home page tidy up

## How to check these changes

Please review the code via Github a local. build is available on my laptop

## Before assigning to reviewer, please make sure you have

- [x] Checked things thoroughly myself before handing over to reviewer.
- [ ] Included the ticket number in the PR title to help us keep track of changes.
- [x] Ensured that PR includes only commits relevant to the ticket.
- [x] Waited for all CI jobs to pass before requesting a review.
- [ ] Added/updated tests and documentation where relevant.

## For Reviewer

Once PR is merged, check and arrange to deploy on platform-sh.

2022-10-06 12:58 UTC, sdwilkes commented
HTML and CSS all looks good, but I'm going to suggest @TNA-Allan checks the Python, so I will reassign it to him. Thanks.

2022-10-10 08:54 UTC, TNA-Allan requested changes
1. We could use branch name next time like mentioned in https://nationalarchives.github.io/ds-wagtail/developer-guide/project-conventions/ ex: feature/UN-175-home-page - perhaps with ticket number hyphened though.
2.  What is the full form of `cta`?  Could we use a bit verbose name over here `etna/core/blocks/cta.py`?

2022-10-10 08:54 UTC, TNA-Allan commented on etna/core/blocks/cta.py
> +        icon = "th-large"
Repetitive variables assignment - `help_text` and `icon`

2022-10-10 08:54 UTC, TNA-Allan commented on etna/core/blocks/cta.py
> +# from wagtail.images.blocks import ImageChooserBlock
Dead code commented. Is this required?

2022-10-10 08:54 UTC, TNA-Allan commented on etna/core/blocks/cta.py
> +        template = "collections/blocks/topic_explorer_new.html"
1. Don't know how long a filename will stay `_new` or how to differentiate it from one without `_new`; could we suffix other than `_new`?
2. After adding `Topic Explorer` in for root page - home page, was not able to see `topic_explorer_new.html` in Debug Tool Bar in Preview. Is there any other way to view it?

2022-10-10 08:54 UTC, TNA-Allan commented on etna/core/blocks/cta.py
> +        template = "collections/blocks/time_period_explorer_new.html"
1. Don't know how long a filename will stay `_new` or how to differentiate it from one without `_new`; could we suffix other than `_new`?
2. After adding `Time Period` in for root page - home page, was not able to see `time_period_explorer_new.html` in Debug Tool Bar in Preview. Is there any other way to view it?

2022-10-17 11:10 UTC, LeanneEmans commented
Hi @mozaki1 and @TNA-Allan  and @jamesbiggs 

I believe that Mo originally wrote the Python code. Mo please can you review the comments Allan has made above please?

2022-10-28 15:47 UTC, TNA-Allan requested changes

2022-10-28 15:47 UTC, TNA-Allan commented on etna/home/migrations/0011_add_feature_insights.py
> +# Generated by Django 3.2.14 on 2022-08-02 21:07
As discussed, multiple migrations with 0011xxx : previous fil[e 0011_add_search_image_fields.py](
https://github.com/nationalarchives/ds-wagtail/blob/develop/etna/home/migrations/0011_add_search_image_fields.py) file _etna/home/migrations/0011_add_feature_insights.py_ both ) 0011, and we want to have one single file for migrations 0011, 0012, 0013 changes in this ticket. 
Example  0012_homepage_featured_collections_and_more.py

2022-10-28 15:47 UTC, TNA-Allan commented on etna/home/migrations/0012_merge_20220926_1451.py
> +# Generated by Django 4.0.7 on 2022-09-26 14:51
same as comment for 0011_add_feature_insights.py

2022-10-28 15:47 UTC, TNA-Allan commented on etna/home/migrations/0013_alter_homepage_body.py
> +# Generated by Django 4.0.7 on 2022-09-30 12:47
same as comment for 0011_add_feature_insights.py

2022-10-28 16:52 UTC, mozaki1 commented on etna/core/blocks/cta.py
> +# from wagtail.images.blocks import ImageChooserBlock
The name was here always and not part of this work.

2022-10-31 11:03 UTC, TNA-Allan commented on etna/home/migrations/0011_add_feature_insights.py
> +# Generated by Django 3.2.14 on 2022-08-02 21:07
Got an error `django.db.utils.ProgrammingError: column "search_image_id" of relation "home_homepage" already exists`
Fix:
Restore `0011_add_search_image_fields.py`
Delete `0012xx`
Get Staging Data and run new migrations which creates new  `0012_homepage_featured_collections_and_more.py`

2022-10-31 11:09 UTC, TNA-Allan requested changes

2022-10-31 11:09 UTC, TNA-Allan commented on templates/insights/blocks/featured_collection_new.html
> +{% load wagtailimages_tags %}
templates/insights/blocks/featured_collection_new.html looks unused. Please check if required.

2022-11-01 08:55 UTC, TNA-Allan commented
Reviewed last feedback. Looks good. Passing to FE as per notes 31/10 on ticket.

2022-11-01 09:00 UTC, TNA-Allan approved these changes
Looks Good. Thanks

2022-11-01 09:00 UTC, merged