Draft: [DF-376] Tracking when a user sorts results or changes result view
nationalarchives/ds-wagtail pull request #779
Opened 2023-04-05 14:44 UTC by janehughes

Ticket URL: paste URL here

## About these changes

Add a human-readable description here

## How to check these changes

Where possible, provide guidance to help your reviewer

## Before assigning to reviewer, please make sure you have

- [ ] Checked things thoroughly before handing over to reviewer.
- [ ] Checked PR title starts with ticket number as per project conventions to help us keep track of changes.
- [ ] Ensured that PR includes only commits relevant to the ticket.
- [ ] Waited for all CI jobs to pass before requesting a review.
- [ ] Added/updated tests and documentation where relevant.

## Merging PR guidance

Follow [docs\developer-guide\contributing.md](https://nationalarchives.github.io/ds-wagtail/developer-guide/contributing/)

## Deployment guidance

Follow [docs\infra\environments.md](https://nationalarchives.github.io/ds-wagtail/infra/environments/)

2023-04-06 15:42 UTC, ababic commented on templates/search/blocks/search_filters.html
We should really generate this value in Python and include it in the context. The various views can then override where the value comes from.

2023-04-11 08:19 UTC, janehughes commented on templates/search/blocks/search_filters.html
That would be ideal if possible @ababic

2023-04-11 11:40 UTC, ababic commented on templates/search/blocks/search_sort_and_view_options.html
> +    <form method="GET" class="search-sort-view__form search-sort-view__desktop" data-id="sort-form" id="catalogue-sort-form-desktop" data-search-type="{% with request.resolver_match.url_name as url_n
```suggestion
    <form method="GET" class="search-sort-view__form search-sort-view__desktop" data-id="sort-form" id="catalogue-sort-form-desktop" data-search-type="{{ view.search_tab }}" data-search-bucket="{{ buckets.current.label }}" data-search-filter-name="Sort results" data-search-filter-value="">
```

2023-04-11 11:41 UTC, ababic requested changes
@janehughes Looks like this value was already being set for datalayer generation, so it should 
 already be possible to access it from the view instance directly

2023-04-14 18:32 UTC, ababic commented on templates/search/blocks/search_sort_and_view_options.html
> +                <a href="?{% query_string_include 'display' 'list' %}" id="listview" search-type="{% with request.resolver_match.url_name as url_name %}{% if url_name == 'search-featured' %}{{ search
```suggestion
                <a href="?{% query_string_include 'display' 'list' %}" id="listview" search-type="{{ view.search_tab }}" search-bucket="{{ buckets.current.label }}" search-filter-name="Sort results" search-filter-value="Display results as a list" class="search-sort-view__icon">
```

2023-04-14 18:33 UTC, ababic commented on templates/search/blocks/search_sort_and_view_options.html
> +                <a href="?{% query_string_include 'display' 'grid' %}" id="gridView" search-type="{% with request.resolver_match.url_name as url_name %}{% if url_name == 'search-featured' %}{{ search
```suggestion
                <a href="?{% query_string_include 'display' 'grid' %}" id="gridView" search-type="{{ view.search_tab }}" search-bucket="{{ buckets.current.label }}" search-filter-name="Sort results" search-filter-value="Display results as a grid" class="search-sort-view__icon">
```

2023-04-24 12:21 UTC, ababic approved these changes
If the right values are displaying in the right places, this is all good from my perspective :)

2023-04-27 08:01 UTC, merged