Feature/un 646 record article promo
nationalarchives/ds-wagtail pull request #934
Opened 2023-05-24 16:14 UTC by nicklee

Ticket URL: https://national-archives.atlassian.net/jira/software/c/projects/UN/boards/75?modal=detail&selectedIssue=UN-646
## About these changes

Adding record revealed component to the highlight gallery page

## How to check these changes

Add a record to the highlight gallery page

<img width="1739" alt="Screenshot 2023-05-24 at 17 13 06" src="https://github.com/nationalarchives/ds-wagtail/assets/298766/204596a8-c99a-45bc-b6a0-73fc5a61a531">

## Before assigning to reviewer, please make sure you have

- [ ] Checked things thoroughly before handing over to reviewer.
- [ ] Checked PR title starts with ticket number as per project conventions to help us keep track of changes.
- [ ] Ensured that PR includes only commits relevant to the ticket.
- [ ] Waited for all CI jobs to pass before requesting a review.
- [ ] Added/updated tests and documentation where relevant.

## Merging PR guidance

Follow [docs\developer-guide\contributing.md](https://nationalarchives.github.io/ds-wagtail/developer-guide/contributing/)

## Deployment guidance

Follow [docs\infra\environments.md](https://nationalarchives.github.io/ds-wagtail/infra/environments/)

2023-05-25 11:08 UTC, William-Blackie submitted a review, later dismissed
Hey @nicklee, this looks good, just some suggestions / double checking. Thanks!

2023-05-25 11:08 UTC, William-Blackie commented on templates/includes/record-revealed.html
> +        <a href="{{ record.record.url }}" class="featured-record-article__link">
Note: Looking at tabbing for this element this link does not have an `active` psudeo state. Could we add one as it's not clear for our screen reader users.

2023-05-25 11:08 UTC, William-Blackie commented on templates/includes/record-revealed.html
> +        <a href="{{ record.record.url }}" class="featured-record-article__link">
Also, it looks like the typography styles is overidding our link colour here; 
![Screenshot from 2023-05-25 12-02-48](https://github.com/nationalarchives/ds-wagtail/assets/22497837/8d347f9f-e44f-403f-914f-16ea12bff94d)

We might need a more specific selector here to override it, or removing that blanket style which would be my preference as we mostly just override it anyway.

2023-05-25 11:08 UTC, William-Blackie commented on templates/includes/record-revealed.html
> +                {% image record.teaser_image fill-626x486-c100 as mobile_img %}
Note: Looking at the designs again, I think we've made this image slighty smaller in width, potentially worth double checking while we're here.

2023-06-05 15:15 UTC, nicklee commented on templates/includes/record-revealed.html
> +{# TODO this is a near duplicate of template/blocks/featured_record_article.html #}
Thanks, I've fixed this so we're now using the include as the main component, with the block referencing the include

2023-06-07 13:16 UTC, jamesbiggs requested changes
Hi @nicklee, there are a few errors in the `_highlight-gallery.scss` that are preventing it from running - I've added a commit that seems to fix it - if you wouldn't mind double checking it and making sure I've not missed anything out/deleted anything that was needed 😃 

I also wrapped it in a div with the `container` class to give it a bit of padding as it's currently stretching further than other page components are.

2023-06-07 15:49 UTC, janehughes approved these changes
This seems good to go to me - I've added one tiny change to vertically center the content in the featured record

2023-06-07 16:04 UTC, jamesbiggs approved these changes

2023-06-07 16:06 UTC, merged